/**
 * Known-answer tests proving the browser implementation of protocol v2
 * produces exactly the bytes the Go implementation does.
 *
 * The vectors are generated by internal/network/vectors_test.go from the
 * production code paths. If the Go side changes the wire format, its own
 * test fails first; if only this side drifts, these fail. Either way the
 * two implementations cannot silently diverge, which is the entire point:
 * a mismatch would otherwise surface as an opaque "authentication failed"
 * during a real transfer.
 */

import { describe, expect, it } from "vitest";
import { x25519 } from "@noble/curves/ed25519.js";

import vectors from "./vectors/protocol-v2.json";
import {
  AAD,
  ChunkedFrameReader,
  ChunkedFrameWriter,
  chunkNonce,
  concatBytes,
  deriveSharedSecret,
  framedLength,
  fromBase64,
  fromHex,
  hkdfExpand,
  importAesKey,
  openEnvelope,
  sealEnvelope,
  sessionFingerprint,
  toBase64,
  toHex,
  type Envelope,
} from "./crypto";

const textEncoder = new TextEncoder();

async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes as BufferSource);
  return toHex(new Uint8Array(digest));
}

/** Reproduces the large vector's plaintext recipe: byte[i] = i % 251. */
function patternBytes(length: number): Uint8Array {
  const out = new Uint8Array(length);
  for (let i = 0; i < length; i++) out[i] = i % 251;
  return out;
}

describe("X25519 key agreement", () => {
  it("derives the same public keys as Go", () => {
    const alicePriv = fromHex(vectors.x25519.alice_private_hex);
    const bobPriv = fromHex(vectors.x25519.bob_private_hex);
    expect(toHex(x25519.getPublicKey(alicePriv))).toBe(
      vectors.x25519.alice_public_hex,
    );
    expect(toHex(x25519.getPublicKey(bobPriv))).toBe(
      vectors.x25519.bob_public_hex,
    );
  });

  it("derives the same raw ECDH output as Go", () => {
    const alicePriv = fromHex(vectors.x25519.alice_private_hex);
    const bobPub = fromHex(vectors.x25519.bob_public_hex);
    expect(toHex(x25519.getSharedSecret(alicePriv, bobPub))).toBe(
      vectors.x25519.raw_ecdh_hex,
    );
  });

  // crypto.go hashes the raw ECDH output before using it as key material.
  // Skipping that hash is the single easiest way to produce a client that
  // looks correct and cannot talk to anything.
  it("hashes the ECDH output into the shared secret", async () => {
    const shared = await deriveSharedSecret(
      fromHex(vectors.x25519.alice_private_hex),
      fromHex(vectors.x25519.bob_public_hex),
    );
    expect(toHex(shared)).toBe(vectors.x25519.shared_hex);
  });

  it("agrees in both directions", async () => {
    const forward = await deriveSharedSecret(
      fromHex(vectors.x25519.alice_private_hex),
      fromHex(vectors.x25519.bob_public_hex),
    );
    const reverse = await deriveSharedSecret(
      fromHex(vectors.x25519.bob_private_hex),
      fromHex(vectors.x25519.alice_public_hex),
    );
    expect(toHex(forward)).toBe(toHex(reverse));
  });
});

describe("HKDF-Expand", () => {
  // WebCrypto's HKDF performs extract+expand; Go's hkdf.Expand does not.
  // Using crypto.subtle.deriveBits here would pass no vector.
  it.each(vectors.hkdf_expand)(
    "derives the key for info $info",
    async ({ info_hex, key_hex }) => {
      const derived = await hkdfExpand(
        fromHex(vectors.x25519.shared_hex),
        fromHex(info_hex),
      );
      expect(toHex(derived)).toBe(key_hex);
    },
  );

  it("supports outputs longer than one HMAC block", async () => {
    const long = await hkdfExpand(
      fromHex(vectors.x25519.shared_hex),
      textEncoder.encode("bonjou/v2/envelope"),
      64,
    );
    expect(long.length).toBe(64);
    // The first block must match the 32-byte derivation exactly.
    expect(toHex(long.subarray(0, 32))).toBe(vectors.hkdf_expand[0].key_hex);
  });

  it("rejects an empty secret", async () => {
    await expect(
      hkdfExpand(new Uint8Array(0), textEncoder.encode("x")),
    ).rejects.toThrow(/empty secret/);
  });
});

describe("envelope sealing", () => {
  it("produces the same ciphertext as Go for a fixed nonce", async () => {
    const key = await importAesKey(fromHex(vectors.envelope.key_hex));
    const ciphertext = new Uint8Array(
      await crypto.subtle.encrypt(
        {
          name: "AES-GCM",
          iv: fromHex(vectors.envelope.nonce_hex) as BufferSource,
          additionalData: textEncoder.encode(AAD) as BufferSource,
          tagLength: 128,
        },
        key,
        textEncoder.encode(vectors.envelope.plaintext_json) as BufferSource,
      ),
    );
    expect(toBase64(ciphertext)).toBe(vectors.envelope.ciphertext_b64);
  });

  it("opens an envelope sealed by Go", async () => {
    const envelope = await openEnvelope(
      vectors.envelope.sealed_json,
      fromHex(vectors.x25519.shared_hex),
    );
    const expected = JSON.parse(vectors.envelope.plaintext_json) as Envelope;
    expect(envelope).toEqual(expected);
    expect(envelope.name).toBe("report.pdf");
    expect(envelope.size).toBe(1048576);
  });

  it("round-trips its own output", async () => {
    const shared = fromHex(vectors.x25519.shared_hex);
    const envelope: Envelope = {
      kind: "file_offer",
      from: "ada",
      from_ip: "",
      to: "bob",
      name: "notes.txt",
      size: 42,
      ts: 1767225600,
      message: "",
      checksum: "",
      hmac: "",
    };
    const sealed = await sealEnvelope(envelope, shared);
    expect(await openEnvelope(sealed, shared)).toEqual(envelope);
  });

  // The version is bound as AAD precisely so this fails.
  it("rejects a downgraded version", async () => {
    const shared = fromHex(vectors.x25519.shared_hex);
    const tampered = JSON.stringify({
      ...JSON.parse(vectors.envelope.sealed_json),
      v: 1,
    });
    await expect(openEnvelope(tampered, shared)).rejects.toThrow(
      /unsupported envelope version/,
    );
  });

  it("rejects tampered ciphertext", async () => {
    const shared = fromHex(vectors.x25519.shared_hex);
    const sealed = JSON.parse(vectors.envelope.sealed_json);
    const bytes = fromBase64(sealed.c);
    bytes[0] ^= 0xff;
    const tampered = JSON.stringify({ ...sealed, c: toBase64(bytes) });
    await expect(openEnvelope(tampered, shared)).rejects.toThrow();
  });
});

describe("chunk nonces", () => {
  it.each(vectors.chunk_nonces)(
    "matches Go at counter $counter",
    ({ counter, nonce_hex }) => {
      expect(toHex(chunkNonce(BigInt(counter)))).toBe(nonce_hex);
    },
  );
});

describe("chunked AEAD streams", () => {
  it("frames a short stream exactly as Go does", async () => {
    const key = await importAesKey(fromHex(vectors.stream_small.stream_key_hex));
    const writer = new ChunkedFrameWriter(key);
    const framed = await writer.seal(
      fromHex(vectors.stream_small.plaintext_hex),
    );
    expect(toHex(framed)).toBe(vectors.stream_small.framed_hex);
  });

  it("derives the small stream key from the shared secret", async () => {
    const { deriveStreamKey } = await import("./crypto");
    const key = await deriveStreamKey(
      fromHex(vectors.x25519.shared_hex),
      fromHex(vectors.stream_small.stream_id_hex),
    );
    expect(toHex(key)).toBe(vectors.stream_small.stream_key_hex);
  });

  // Spans more than one 64 KiB chunk, so it exercises counter increment
  // and multi-frame output where an independent implementation is most
  // likely to drift.
  it("frames a multi-chunk stream exactly as Go does", async () => {
    const key = await importAesKey(fromHex(vectors.stream_large.stream_key_hex));
    const writer = new ChunkedFrameWriter(key);
    const plaintext = patternBytes(vectors.stream_large.plaintext_size);
    const framed = await writer.seal(plaintext);
    expect(framed.length).toBe(vectors.stream_large.framed_size);
    expect(await sha256Hex(framed)).toBe(vectors.stream_large.framed_sha256);
  });

  it("predicts framed length without doing the work", () => {
    expect(framedLength(vectors.stream_large.plaintext_size)).toBe(
      vectors.stream_large.framed_size,
    );
    expect(framedLength(vectors.stream_small.plaintext_size)).toBe(
      vectors.stream_small.framed_hex.length / 2,
    );
    expect(framedLength(0)).toBe(0);
  });

  it("reads back what it wrote, including across arbitrary splits", async () => {
    const key = await importAesKey(fromHex(vectors.stream_large.stream_key_hex));
    const plaintext = patternBytes(vectors.stream_large.plaintext_size);
    const framed = await new ChunkedFrameWriter(key).seal(plaintext);

    // Feed the reader in awkward slices: a real network delivers frames
    // split at arbitrary boundaries, not on frame edges.
    const reader = new ChunkedFrameReader(key);
    const pieces: Uint8Array[] = [];
    const sliceSize = 7919; // prime, so it never aligns with frame edges
    for (let offset = 0; offset < framed.length; offset += sliceSize) {
      pieces.push(
        await reader.push(framed.subarray(offset, offset + sliceSize)),
      );
    }
    expect(reader.pending).toBe(0);
    expect(toHex(concatBytes(...pieces))).toBe(toHex(plaintext));
  });

  it("rejects a tampered chunk before yielding plaintext", async () => {
    const key = await importAesKey(fromHex(vectors.stream_small.stream_key_hex));
    const framed = fromHex(vectors.stream_small.framed_hex);
    framed[framed.length - 1] ^= 0xff;
    const reader = new ChunkedFrameReader(key);
    await expect(reader.push(framed)).rejects.toThrow(
      /chunk authentication failed/,
    );
  });

  it("rejects an oversized frame header", async () => {
    const key = await importAesKey(fromHex(vectors.stream_small.stream_key_hex));
    const bogus = new Uint8Array(8);
    new DataView(bogus.buffer).setUint32(0, 0xffffff, false);
    const reader = new ChunkedFrameReader(key);
    await expect(reader.push(bogus)).rejects.toThrow(/exceeds max/);
  });
});

describe("session fingerprint", () => {
  it("is stable regardless of which side computes it", async () => {
    const a = fromHex(vectors.x25519.alice_public_hex);
    const b = fromHex(vectors.x25519.bob_public_hex);
    expect(await sessionFingerprint(a, b)).toBe(
      await sessionFingerprint(b, a),
    );
  });

  it("renders as colon-separated hex pairs like the CLI", async () => {
    const fingerprint = await sessionFingerprint(
      fromHex(vectors.x25519.alice_public_hex),
      fromHex(vectors.x25519.bob_public_hex),
    );
    expect(fingerprint).toMatch(/^([0-9a-f]{2}:){7}[0-9a-f]{2}$/);
  });

  it("changes if either key changes", async () => {
    const a = fromHex(vectors.x25519.alice_public_hex);
    const b = fromHex(vectors.x25519.bob_public_hex);
    const c = new Uint8Array(b);
    c[0] ^= 0xff;
    expect(await sessionFingerprint(a, b)).not.toBe(
      await sessionFingerprint(a, c),
    );
  });
});
